#!/usr/bin/env bash
#

CP="$(cpof ./lib_managed/jars/org.scala-miniboxing.plugins):$(cpof build/quick/classes):$(cpof build/deps)"
PROGRAM="scala.tools.nsc.Main"
MINIBOX=$(ls ./lib_managed/jars/org.scala-miniboxing.plugins/miniboxing-plugin_*/*.jar)

java -classpath "$CP" \
  "$PROGRAM" \
  -usejavacp \
  -P:minibox:hijack -P:minibox:log -P:minibox:stats -Xplugin:$MINIBOX \
  -optimize \
  "$@"
